Update deploy-workflow.yml

diff --git a/.github/workflows/deploy-workflow.yml b/.github/workflows/deploy-workflow.yml
--- a/.github/workflows/deploy-workflow.yml
+++ b/.github/workflows/deploy-workflow.yml
@@ -4,6 +4,7 @@ on:
   push:
     branches:
       - 'main' # Déclenche le workflow lors des pushs sur la branche "main"
+      - '#WS-69-workflow'
 
 env:
   EC2_USER: ec2-user # Utilisateur SSH sur ton serveur EC2
@@ -21,7 +22,7 @@ jobs:
 
     steps:
       - name: Checkout code
-        uses: actions/checkout@v4
+        uses: actions/checkout@v4 # Récupérer le code depuis le dépôt GitHub
 
       - name: Set up JDK 17
         uses: actions/setup-java@v3.1.1
@@ -32,7 +33,7 @@ jobs:
       - name: Check Java version
         run: java -version # Vérifie la version de Java utilisée par GitHub Actions
 
-      - name: Setup SSH key for EC2
+      - name: Setup SSH
         run: |
           echo "${{ secrets.EC2_PRIVATE_KEY }}" > github-ec2.pem
           chmod 600 github-ec2.pem
@@ -44,12 +45,38 @@ jobs:
       - name: Build the app
         run: |
           ./mvnw -Pprod clean verify
+          
+      - name: Backup existing JAR on EC2 if it exists
+        run: |
+          ssh -o StrictHostKeyChecking=no -i github-ec2.pem $EC2_USER@${{ secrets.EC2_HOST }} "
+            if [ -f ${{ env.APP_DIR }}/${{ env.JAR_NAME }} ]; then
+              echo 'Backing up existing JAR file.'
+              mv ${{ env.APP_DIR }}/${{ env.JAR_NAME }} ${{ env.APP_DIR }}/${{ env.JAR_NAME }}.backup
+            else
+              echo 'No existing JAR file to back up.'
+            fi
+          "
+          
       - name: Transfer JAR to EC2
         run: |
           scp -o StrictHostKeyChecking=no -i github-ec2.pem target/${{ env.JAR_NAME }} $EC2_USER@${{ secrets.EC2_HOST }}:${{ env.APP_DIR }}/${{ env.JAR_NAME }}
       - name: Restart application on EC2
         run: |
           ssh -o StrictHostKeyChecking=no -i github-ec2.pem $EC2_USER@${{ secrets.EC2_HOST }} "
-            sudo systemctl stop weebSportAppService.service &&  # Arrêter le service de l'application
-            sudo systemctl restart weebSportAppService.service  # Redémarrer le service de l'application
+            sudo systemctl restart weebSportAppService.service &&
+            sleep 5 &&
+            if systemctl is-active --quiet weebSportAppService.service; then
+              echo 'weebSportAppService service started successfully.'
+            else
+              echo 'weebSportAppService service failed to start.'
+              if [ -f ${{ env.APP_DIR }}/${{ env.JAR_NAME }}.backup ]; then
+                echo 'Restoring backup JAR.'
+                mv ${{ env.APP_DIR }}/${{ env.JAR_NAME }}.backup ${{ env.APP_DIR }}/${{ env.JAR_NAME }}
+                sudo systemctl restart weebSportAppService.service
+                exit 1
+              else
+                echo 'No backup JAR available. Exiting.'
+                exit 1
+              fi
+            fi
           "
